{% set name = "yieldfrom" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/yieldfrom-{{ version }}.tar.gz
  sha256: eb75e58641410f06083f85013a438f28bceaabfe5af9c3206d5049362c37aca0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - yieldfrom
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Nurdok/yieldfrom/
  summary: A backport of the `yield from` semantic from Python 3.x to Python 2.7
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ruben-arts
